"""Deny rules written out as instructions for agents that don't read settings.json.
Pure functions over a list of rule strings and a project root, no sous imports."""
import os
import re
import shutil
import tempfile

# Other agents (Codex, Cursor, Copilot) don't read settings.json. The deny rules
# are the policy; this writes them out as instructions those agents do read. It
# is a request, not a control: only Claude Code enforces them.
COMPILE_BEGIN = "<!-- sous:begin (generated by `sous compile`; change .claude/settings.json, then rerun) -->"
COMPILE_END = "<!-- sous:end -->"
COMPILE_TARGETS = {
    "agents": ("AGENTS.md", False),
    "copilot": (".github/copilot-instructions.md", False),
    "cursor": (".cursor/rules/sous.mdc", True),
}
GUARD_STOPS = [
    "Never run a recursive force delete (`rm -rf`, however it is spelled or wrapped in `sh -c`).",
    "Never run a force, mirror or delete push.",
    "Never read a secrets file (`.env`, SSH keys), including through `sh -c` or `python -c`.",
    "Never pipe fetched or generated text into a shell.",
]


def compile_text(deny):
    runs, reads, edits, other, kept = [], [], [], [], []
    for rule in deny:
        m = re.match(r"^(\w+)\((.*)\)$", rule)
        if not m:
            other.append(rule)
            continue
        tool, inner = m.groups()
        if tool in ("Read", "Edit") and inner.startswith("!"):
            kept.append(inner[1:])
        elif tool == "Bash":
            runs.append(inner[:-2] if inner.endswith(":*") else inner)
        elif tool == "Read":
            reads.append(inner)
        elif tool == "Edit":
            edits.append(inner)
        else:
            other.append(rule)
    out = ["## Stops (from sous)", "",
           "Do not do these, and do not look for a way around them. If one blocks the task, stop and ask.", ""]
    out += [f"- {g}" for g in GUARD_STOPS]
    out += [f"- Never run `{c}`." for c in runs]
    out += [f"- Never read `{c}`." for c in reads]
    out += [f"- Never edit `{c}`." for c in edits]
    out += [f"- Never use `{c}`." for c in other]
    if kept:
        out.append(f"- Exceptions: {', '.join('`' + k + '`' for k in sorted(set(kept)))} may be read or edited.")
    return "\n".join(out)


class MarkerError(Exception):
    """The target's sous markers are not one begin/end pair (or a file sous owns
    lacks them), so sous can't tell its block from the user's text."""


def write_text_atomic(path, text):
    """Temp file and rename, as bin/sous's write_json_atomic: a symlinked file
    (AGENTS.md -> CLAUDE.md) is written through, and an existing file keeps its mode."""
    path = os.path.realpath(path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".sous-", suffix=".tmp", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
        if os.path.exists(path):
            shutil.copymode(path, tmp)
        else:
            mask = os.umask(0)
            os.umask(mask)
            os.chmod(tmp, 0o666 & ~mask)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def check_markers(rel, text):
    """Raise MarkerError unless text has no sous block or exactly one, begin before end."""
    b, e = text.count(COMPILE_BEGIN), text.count(COMPILE_END)
    if (b, e) == (0, 0) or ((b, e) == (1, 1) and text.index(COMPILE_BEGIN) < text.index(COMPILE_END)):
        return
    raise MarkerError(f"{rel} has {b} sous:begin and {e} sous:end marker(s), not one pair; "
                      "fix them by hand so sous can't take your text for its block, then rerun")


def block_re():
    return re.compile(re.escape(COMPILE_BEGIN) + r".*?" + re.escape(COMPILE_END) + r"\n?", re.S)


def render(deny, target):
    """The text for a target: the marked block, behind frontmatter for a file sous owns."""
    body = COMPILE_BEGIN + "\n" + compile_text(deny) + "\n" + COMPILE_END + "\n"
    if COMPILE_TARGETS[target][1]:
        head = "---\ndescription: Stops from the project's Claude Code deny rules (sous)\nalwaysApply: true\n---\n\n"
        return head + body
    return body


def write(root, target, body, n_rules):
    """Write body into the target; returns the message to print."""
    rel, owned = COMPILE_TARGETS[target]
    path = os.path.join(root, rel)
    existing = open(path).read() if os.path.isfile(path) else ""
    if owned and existing and COMPILE_BEGIN not in existing:
        raise MarkerError(f"{rel} exists and has no sous marker, so sous didn't write it; move it aside, then rerun")
    check_markers(rel, existing)
    if owned or not existing:
        new = body
    elif block_re().search(existing):
        new = block_re().sub(lambda _: body, existing, count=1)
    else:
        new = existing.rstrip("\n") + "\n\n" + body
    if new == existing:
        return f"{rel} is up to date"
    write_text_atomic(path, new)
    return f"wrote {rel} from {n_rules} deny rule(s); `sous compile --to={target} --remove` takes it out"


def remove(root, target):
    """Take sous's block (or its own file) out of the target; returns the message to print."""
    rel, owned = COMPILE_TARGETS[target]
    path = os.path.join(root, rel)
    if not os.path.isfile(path):
        return f"sous compile: nothing at {rel}"
    text = open(path).read()
    check_markers(rel, text)
    if owned and COMPILE_BEGIN in text:
        os.remove(path)
        return f"removed {rel}"
    if block_re().search(text):
        rest = block_re().sub("", text).strip("\n")
        if rest:
            write_text_atomic(path, rest + "\n")
            return f"removed the sous block from {rel}"
        os.remove(path)
        return f"removed {rel} (only the sous block was in it)"
    return f"sous compile: no sous block in {rel}"
